package com.example.Camp.enums;

public enum DepartmentType {
    YOUTH_MINISTRIES,
    MIFEM,
    CHILDRENS_MINISTRIES,
    FAMILY_MINISTRIES,
    HEALTH_MINISTRIES,
    MINISTERIAL_ASSOCIATION,
    PUBLISHING_MINISTRIES,
    SABBATH_SCHOOL,
    PERSONAL_MINISTRIES,
    EDUCATION
}
