package com.example.Camp.enums;

public enum NotificationType {
    GENERAL_ANNOUNCEMENT,
    SCHEDULE_UPDATE,
    VENUE_CHANGE,
    EMERGENCY_NOTICE,
    ACCOMMODATION_NOTICE,
    REGISTRATION_CONFIRMATION,
    PAYMENT_CONFIRMATION,
    EVENT_REMINDER,
    SESSION_REMINDER
}
